#!/bin/bash
# =============================================================================
# setup-email.sh — One-command deploy for Mailcow email server
# =============================================================================
#
# Usage:
#   bash setup-email.sh --domain mail.novaframe.cloud --hostname mail.novaframe.cloud --api-key 'SECRET'
#
# Prerequisites:
#   - Fresh Ubuntu 24.04 VPS/VDS
#   - DNS records already pointing to this server:
#       A record:  mail.novaframe.cloud -> <server-ip>
#       MX record: novaframe.cloud -> mail.novaframe.cloud (priority 10)
#   - Port 25, 80, 443, 587, 993, 995, 4190 open
#
# This script:
#   1. Installs Docker + Docker Compose
#   2. Clones and configures Mailcow
#   3. Generates mailcow.conf
#   4. Starts Mailcow services
#   5. Creates an API key
#   6. Configures firewall (ufw)
#   7. Sets up automatic updates via cron
#
# Must be run as root.
# =============================================================================

set -euo pipefail

# ---- Defaults ----
DOMAIN=""
HOSTNAME=""
API_KEY=""
INSTALL_DIR="/opt/mailcow-dockerized"
TIMEZONE="UTC"

# ---- Parse arguments ----
while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain)    DOMAIN="$2";    shift 2 ;;
        --hostname)  HOSTNAME="$2";  shift 2 ;;
        --api-key)   API_KEY="$2";   shift 2 ;;
        --timezone)  TIMEZONE="$2";  shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root"; exit 1
fi
if [[ -z "$DOMAIN" ]]; then
    echo "Error: --domain is required (e.g. mail.novaframe.cloud)"; exit 1
fi
if [[ -z "$HOSTNAME" ]]; then
    HOSTNAME="$DOMAIN"
fi
if [[ -z "$API_KEY" ]]; then
    API_KEY=$(openssl rand -hex 32)
    echo "Generated API key: $API_KEY"
fi

SERVER_IP=$(hostname -I | awk '{print $1}')
echo "============================================"
echo " Mailcow Email Server Setup"
echo " Domain:   $DOMAIN"
echo " Hostname: $HOSTNAME"
echo " Server:   $SERVER_IP"
echo "============================================"

# ---- Step 1: System updates ----
echo "[1/7] Updating system..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq

# ---- Step 2: Install Docker ----
echo "[2/7] Installing Docker..."
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
fi

# Ensure docker compose plugin is available
if ! docker compose version &>/dev/null; then
    apt-get install -y -qq docker-compose-plugin
fi

# ---- Step 3: Set hostname and timezone ----
echo "[3/7] Configuring hostname and timezone..."
hostnamectl set-hostname "$HOSTNAME"
timedatectl set-timezone "$TIMEZONE"

# Ensure hostname resolves
if ! grep -q "$HOSTNAME" /etc/hosts; then
    echo "127.0.0.1 $HOSTNAME" >> /etc/hosts
fi

# ---- Step 4: Clone Mailcow ----
echo "[4/7] Installing Mailcow..."
if [[ -d "$INSTALL_DIR" ]]; then
    echo "Mailcow directory already exists, updating..."
    cd "$INSTALL_DIR"
    git pull --quiet
else
    umask 0022
    cd /opt
    git clone https://github.com/mailcow/mailcow-dockerized.git
    cd "$INSTALL_DIR"
fi

# ---- Step 5: Generate mailcow.conf ----
echo "[5/7] Generating configuration..."
if [[ ! -f mailcow.conf ]]; then
    # Auto-generate config
    cat > mailcow.conf <<CONF
# Mailcow configuration — generated by setup-email.sh
MAILCOW_HOSTNAME=${HOSTNAME}
MAILCOW_PASS_SCHEME=BLF-CRYPT
DBNAME=mailcow
DBUSER=mailcow
DBPASS=$(openssl rand -hex 16)
DBROOT=$(openssl rand -hex 16)
HTTP_PORT=80
HTTP_BIND=0.0.0.0
HTTPS_PORT=443
HTTPS_BIND=0.0.0.0
SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
DOVEADM_PORT=127.0.0.1:19991
SQL_PORT=127.0.0.1:13306
SOLR_PORT=127.0.0.1:18983
REDIS_PORT=127.0.0.1:7654
API_KEY=${API_KEY}
API_KEY_READ_ONLY=${API_KEY}
API_ALLOW_FROM=0.0.0.0/0
TZ=${TIMEZONE}
COMPOSE_PROJECT_NAME=mailcowdockerized
SKIP_LETS_ENCRYPT=n
SKIP_CLAMD=n
SKIP_SOGO=n
SKIP_SOLR=y
SKIP_FTS=y
ENABLE_FTSSOLR=n
ALLOW_ADMIN_EMAIL_LOGIN=y
ACL_ANYONE=disallow
MAILDIR_GC_TIME=7200
ADDITIONAL_SAN=
IPV4_NETWORK=172.22.1
IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
LOG_LINES=9999
WATCHDOG_NOTIFY_EMAIL=
WATCHDOG_NOTIFY_BAN=n
WATCHDOG_EXTERNAL_CHECKS=n
WATCHDOG_SUBJECT=Watchdog ALERT
SNAT_TO_SOURCE=
SNAT6_TO_SOURCE=
COMPOSE_HTTP_TIMEOUT=600
DOCKER_COMPOSE_VERSION=native
CONF
    echo "  mailcow.conf generated"
else
    echo "  mailcow.conf already exists, skipping generation"
    # Update the API key in existing config
    sed -i "s/^API_KEY=.*/API_KEY=${API_KEY}/" mailcow.conf
    sed -i "s/^API_KEY_READ_ONLY=.*/API_KEY_READ_ONLY=${API_KEY}/" mailcow.conf
fi

# ---- Step 6: Start Mailcow ----
echo "[6/7] Starting Mailcow (this may take 5-10 minutes on first run)..."
docker compose pull --quiet 2>/dev/null || true
docker compose up -d

# Wait for services to be healthy
echo "  Waiting for services to start..."
sleep 30

# Check if nginx is responding
for i in {1..30}; do
    if curl -sk https://127.0.0.1/api/v1/get/status/containers -H "X-API-Key: ${API_KEY}" 2>/dev/null | grep -q "type"; then
        echo "  Mailcow API is responding!"
        break
    fi
    echo "  Waiting... ($i/30)"
    sleep 10
done

# ---- Step 7: Configure firewall ----
echo "[7/7] Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw --force reset >/dev/null 2>&1
    ufw default deny incoming
    ufw default allow outgoing
    # SSH
    ufw allow 22/tcp
    # HTTP/HTTPS (for Let's Encrypt + webmail)
    ufw allow 80/tcp
    ufw allow 443/tcp
    # SMTP
    ufw allow 25/tcp
    ufw allow 465/tcp
    ufw allow 587/tcp
    # IMAP/POP
    ufw allow 993/tcp
    ufw allow 995/tcp
    ufw allow 143/tcp
    ufw allow 110/tcp
    # Sieve
    ufw allow 4190/tcp
    ufw --force enable
    echo "  Firewall configured"
fi

# ---- Step 8: Set rDNS reminder ----
echo ""
echo "============================================"
echo " SETUP COMPLETE"
echo "============================================"
echo ""
echo " Mailcow is running at: https://${HOSTNAME}"
echo " Admin login: admin / moohoo (CHANGE THIS!)"
echo " API Key: ${API_KEY}"
echo ""
echo " MANUAL STEPS REQUIRED:"
echo ""
echo " 1. DNS Records (in Cloudflare):"
echo "    A     mail.novaframe.cloud    -> ${SERVER_IP}"
echo "    MX    novaframe.cloud         -> mail.novaframe.cloud (priority 10)"
echo "    TXT   novaframe.cloud         -> v=spf1 a mx ip4:${SERVER_IP} ~all"
echo "    TXT   _dmarc.novaframe.cloud  -> v=DMARC1; p=quarantine; rua=mailto:postmaster@novaframe.cloud"
echo ""
echo " 2. Reverse DNS (PTR record):"
echo "    Set PTR for ${SERVER_IP} -> ${HOSTNAME}"
echo "    (Do this in your VPS provider's panel)"
echo ""
echo " 3. Change admin password:"
echo "    Go to https://${HOSTNAME} and log in with admin/moohoo"
echo "    Change the password immediately!"
echo ""
echo " 4. Environment variables for NovaFrame:"
echo "    MAILCOW_API_URL=https://${HOSTNAME}/api/v1"
echo "    MAILCOW_API_KEY=${API_KEY}"
echo ""
echo "============================================"
